hostname: DC3-SPINE2
metadata:
  platform: vEOS
is_deployed: true
router_bgp:
  as: '65300'
  router_id: 10.3.100.2
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    ebgp_multihop: 3
    next_hop_unchanged: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  neighbors:
  - ip_address: 10.3.0.51
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65301'
    peer: DC3-LEAF1
    description: DC3-LEAF1_Ethernet50/1
  - ip_address: 10.3.0.55
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65301'
    peer: DC3-LEAF2
    description: DC3-LEAF2_Ethernet50/1
  - ip_address: 10.3.0.43
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65316'
    peer: DC3-BORDER1
    description: DC3-BORDER1_Ethernet50/1
  - ip_address: 10.3.0.47
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65316'
    peer: DC3-BORDER2
    description: DC3-BORDER2_Ethernet50/1
  - ip_address: 10.3.101.11
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC3-BORDER1
    description: DC3-BORDER1
    remote_as: '65316'
  - ip_address: 10.3.101.12
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC3-BORDER2
    description: DC3-BORDER2
    remote_as: '65316'
  - ip_address: 10.3.101.13
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC3-LEAF1
    description: DC3-LEAF1
    remote_as: '65301'
  - ip_address: 10.3.101.14
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC3-LEAF2
    description: DC3-LEAF2
    remote_as: '65301'
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
static_routes:
- vrf: management
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.99.99.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 1.1.1.1
  vrf: management
spanning_tree:
  mode: none
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$Nck9evzfm5e9C0Vg$bZ/XSXJ/.ZqJ6NQkPXV3s48IdFB7QS5vzSOYTbmwtenuUKQcFlWgP0lE.uWPPGVMJVA/2Yo8eiRax5mxh7Q0y1
vrfs:
- name: management
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: management
  ip_address: 10.99.99.214/24
  gateway: 10.99.99.1
  type: oob
management_api_http:
  enable_vrfs:
  - name: management
  enable_https: true
ip_domain_lookup:
  source_interfaces:
  - name: Management1
    vrf: management
ethernet_interfaces:
- name: Ethernet1/1
  peer: DC3-LEAF1
  peer_interface: Ethernet50/1
  peer_type: l3leaf
  description: P2P_LINK_TO_DC3-LEAF1_Ethernet50/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.3.0.50/31
- name: Ethernet2/1
  peer: DC3-LEAF2
  peer_interface: Ethernet50/1
  peer_type: l3leaf
  description: P2P_LINK_TO_DC3-LEAF2_Ethernet50/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.3.0.54/31
- name: Ethernet7/1
  peer: DC3-BORDER1
  peer_interface: Ethernet50/1
  peer_type: l3leaf
  description: P2P_LINK_TO_DC3-BORDER1_Ethernet50/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.3.0.42/31
- name: Ethernet8/1
  peer: DC3-BORDER2
  peer_interface: Ethernet50/1
  peer_type: l3leaf
  description: P2P_LINK_TO_DC3-BORDER2_Ethernet50/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.3.0.46/31
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 10.3.100.2/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.3.100.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
