---
#Fabric name
fabric_name: DC3

#define local users
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: "$6$Nck9evzfm5e9C0Vg$bZ/XSXJ/.ZqJ6NQkPXV3s48IdFB7QS5vzSOYTbmwtenuUKQcFlWgP0lE.uWPPGVMJVA/2Yo8eiRax5mxh7Q0y1"

# Timezone
clock:
  timezone: CST

# Management parameters
mgmt_interface_vrf: management
mgmt_gateway: 10.99.99.1

# Streaming agent configuration
daemon_terminattr:
  cvaddrs:
    - apiserver.arista.io:443
  cvauth:
    method: "token-secure"
    token_file: "/mnt/flash/cv-onboarding-token"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  cvvrf: management
  disable_aaa: true

# DNS servers.
name_servers:
  - 1.1.1.1

dns_domain: home.dime-a-tron.com

# NTP Servers
ntp:
  local_interface:
    name: Management1
    vrf: management
  servers:
  - name: 0.pool.ntp.org
    iburst: true
    vrf: management

# Reuse same IP for mlag L2 and L3 peering
fabric_ip_addressing:
  mlag:
    algorithm: first_id

#aaa authorization exec
aaa_authorization:
  exec:
    default: local

# Default Source Interfaces for Control-Plane Traffic
source_interfaces:
  domain_lookup:
    mgmt_interface: true

# cEOS-lab MTU Overrid
p2p_uplinks_mtu: 1500