---
- name: Configuration deployment with CVP
  hosts: CVaaS
  connection: local
  gather_facts: false

  tasks:
    - name: run CVP provisioning
      import_role:
          name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'dcapetz'
        configlets_prefix: 'dcapetz - AVD'
        state: present
