---
tenants: 
#############################################
# Internal Corporate Shared Services Tenant #
#############################################
  - name: CORP
    mac_vrf_vni_base: 10000 
    enable_mlag_ibgp_peering_vrfs: false
    vrfs: 
      - name: CORP
        vrf_vni: 5001
        svis: 
          - id: 101
            name: CORP_Services_101
            enabled: true
            ip_address_virtual: 10.101.101.1/24
#################################
# Public Facing Services Tenant #
#################################
  - name: PUBLIC
    mac_vrf_vni_base: 10000 
    enable_mlag_ibgp_peering_vrfs: false
    vrfs: 
      - name: PUBLIC
        vrf_vni: 5002
        svis: 
          - id: 201
            name: PUBLIC_Services_201
            enabled: true
            ip_address_virtual: 10.201.201.1/24